# ------------------------------------------------------------
# Compiler + global settings
# ------------------------------------------------------------
CC       := gcc
SRC_DIR  := src
BUILD_DIR := build
BIN      := $(BUILD_DIR)/etherskies

# Compiler flags:
#  -std=c11   : C11 standard
#  -Wall -Wextra : warnings
#  -MMD -MP  : auto-generate dependency files
#  -Isrc/libs : include your project headers
#  -Isrc/jansson/src : include Jansson headers directly from its src folder
CFLAGS   := -std=c11 -Wall -Wextra -MMD -MP -Ilib/jansson  -Isrc/libs -Iincludes -Wno-format-truncation -g

# Linker flags and libraries
LDFLAGS  := -flto -Wl,--gc-sections
LIBS     := -lcurl


# ------------------------------------------------------------
# Source and object files
# ------------------------------------------------------------

# Find all project .c files under src/
SRC      := $(shell find -L $(SRC_DIR) -type f -name '*.c' ! -path "*/jansson/*")

# Map each .c to a .o file in the build directory
OBJ      := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRC))

# Dependency files generated by -MMD
DEP      := $(OBJ:.o=.d)


# ------------------------------------------------------------
# Jansson integration
# ------------------------------------------------------------
# Only compile Jansson files inside src/jansson/src/
# (exclude doc/, examples/, test/, etc.)
JANSSON_SRC := $(shell find lib/jansson/ -maxdepth 1 -type f -name '*.c')

# Map Jansson .c -> build/jansson/*.o
JANSSON_OBJ := $(patsubst lib/jansson/%.c,$(BUILD_DIR)/jansson/%.o,$(JANSSON_SRC))

# Add them to global object list
OBJ += $(JANSSON_OBJ)


# ------------------------------------------------------------
# Build rules
# ------------------------------------------------------------

# Default target
all: $(BIN)
	@echo "Build complete."

# Link all objects into final binary
$(BIN): $(OBJ)
	@$(CC) $(LDFLAGS) $(OBJ) -o $@ $(LIBS)

# Compile your project .c files
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@echo "Compiling $<..."
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -c $< -o $@

# Compile Jansson .c files
$(BUILD_DIR)/jansson/%.o: lib/jansson/%.c
	@echo "Compiling Jansson $<..."
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -c $< -o $@


# ------------------------------------------------------------
# Utilities
# ------------------------------------------------------------
run: $(BIN)
	./$(BIN)

clean:
	@rm -rf $(BUILD_DIR) $(BIN)

# Include auto-generated dependency files
-include $(DEP)

.PHONY: all run clean print
